name: Build on linux with Coveralls and SonarCloud

on: pull_request
 
jobs:
    sonarcloud:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
          with:
            # Disabling shallow clone is recommended for improving relevancy of reporting
            fetch-depth: 0
        - name: SonarCloud Scan
          uses: sonarsource/sonarcloud-github-action@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    
    build:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            java: [ 11, 15 ]
        
        name: Build with Java ${{ matrix.java }} on ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Set up JDK ${{ matrix.java }}
          uses: actions/setup-java@v1
          with:
            java-version: ${{ matrix.java }}
        - name: Cache Maven packages
          uses: actions/cache@v2
          with:
            path: |
              ~/.m2
              ~/.sonar/cache
            key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml, **/*.yaml') }}
            restore-keys: ${{ runner.os }}-m2-
        - name: Build with Maven then push to Coveralls and SonarCloud
          run: >
            mvn verify
            -Pcoveralls 
            -DrepoToken=$COVERALLS_REPO_TOKEN 
          env: 
            COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}