name: PR build on linux with Java 11, Coveralls and SonarCloud

on:
  pull_request:
 
jobs: 
  build:
    runs-on: ubuntu-20.04
        
    name: Build with Java 11 on ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2
          ~/.sonar/cache
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml, **/*.yaml') }}
        restore-keys: ${{ runner.os }}-m2-
    - name: Install TightVNC
      run: |
        sudo apt-get install tightvncserver
        curl https://github.com/croesch/beefiles/raw/master/src/execute-on-vnc.sh --output execute-on-vnc.sh
        chmod +x execute-on-vnc.sh
    - name: Build with Maven then push to Coveralls and SonarCloud
      run: >
        ./execute-on-vnc.sh mvn verify
        org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
        -Pcoveralls 
        -DrepoToken=$COVERALLS_REPO_TOKEN
        -Dsonar.projectKey=MassimilianoMancini_libretto
        -DpullRequest=${{ github.event.pull_request.number }}
      env: 
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}}        
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
   