name: Build on Mac

on:
    push:
      tags:
        - v*
    
jobs:
    build:
        runs-on: macos-11
        strategy:
          matrix:
            java: [ 11, 15 ]
        
        name: Build with Java ${{ matrix.java }} on macos-latest
        steps:
        - uses: actions/checkout@v2
        - name: Set up JDK ${{ matrix.java }}
          uses: actions/setup-java@v1
          with:
            java-version: ${{ matrix.java }}
        - name: Install Docker
          uses: docker-practice/actions-setup-docker@master
        - name: Cache Maven packages
          uses: actions/cache@v2
          with:
            path: ~/.m2
            key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml, **/*.yaml') }}
            restore-keys: ${{ runner.os }}-m2-
        - name: Create symbolic links for mariadb4j bug
          run: >
            ln -s /usr/lib/libcrypto.dylib /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
            ln -s /usr/lib/libssl.dylib /usr/local/opt/openssl/lib/libssl.1.0.0.dylib 
        - name: Build with Maven
          run: mvn verify