name: Windows / Java 11, 15

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2019
    strategy:
      matrix:
        java: [11, 15]
    name: Build with Java ${{ matrix.java }} on windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml, **/*.yaml') }}
        restore-keys: ${{ runner.os }}-m2-
    - name: Docker config and restart
      run: |
          sc config docker binpath="dockerd.exe --run-service -H tcp://localhost:2375"
          restart-service *docker*
    - name: Build with Maven
      run: mvn verify -P windows-container
      working-directory: libretto